# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5954c795d46de7a52a4d925675e1fb73d28521a83b00c43e74a7fd292e40b2b05f9a8361599341614f60030945d1eee712c714c384c315ae36527a707ed00edd

test:
  secret_key_base: 397f177d1a775ee385cf578f351b7564eda4ae62d80e0376ec26e8f4786d8cf61abf1769fe2bcae332bc9eaaf55d53e988e62ab839ce5b9f024fc1fd1faac2ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
